image: ubuntu:18.04

stages:
  - linux_dedicated
  - linux_desktop
  - coverity_scan

variables:
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  key: $CI_JOB_NAME
  paths:
    - ccache

linux_dedicated:
  stage: linux_dedicated
  before_script:
  - dpkg --add-architecture i386
  - apt update
  - apt install -y git cmake ccache p7zip-full gcc-multilib g++-multilib build-essential zlib1g:i386 libstdc++6:i386
  - mkdir -p ccache
  - export PATH="/usr/lib/ccache:$PATH"
  - export CCACHE_BASEDIR="$PWD"
  - export CCACHE_DIR="$PWD/ccache"
  - export CCACHE_COMPILERCHECK=content
  - ccache --zero-stats || true
  - ccache --show-stats || true
  after_script:
  - export CCACHE_DIR="$PWD/ccache"
  - ccache --show-stats
  script:
  - mkdir out2
  - cd out2
  - export CC="gcc -m32"
  - export CXX="gcc -m32"
  - cmake -DXASH_DOWNLOAD_DEPENDENCIES=yes -DXASH_SDL=OFF -DXASH_DEDICATED=ON -DXASH_STATIC=ON -DXASH_DLL_LOADER=ON -DXASH_VGUI=OFF -DCMAKE_BUILD_TYPE=RelWithDebInfo ../
  - make -j$(nproc --all)
  artifacts:
    paths:
    - out2/engine/xash3d

linux_desktop:
  stage: linux_desktop
  before_script:
  - dpkg --add-architecture i386
  - apt update
  - apt install -y git curl ccache cmake p7zip-full gcc-multilib g++-multilib build-essential libx11-dev:i386 libxext-dev:i386 libgl1-mesa-dev libasound-dev zlib1g:i386 libstdc++6:i386
  - mkdir -p ccache
  - export PATH="/usr/lib/ccache:$PATH"
  - export CCACHE_BASEDIR="$PWD"
  - export CCACHE_DIR="$PWD/ccache"
  - export CCACHE_COMPILERCHECK=content
  - ccache --zero-stats || true
  - ccache --show-stats || true
  after_script:
  - export CCACHE_DIR="$PWD/ccache"
  - ccache --show-stats
  script:
  - curl -s http://libsdl.org/release/SDL2-2.0.14.tar.gz | tar xzf -
  - cd $CI_PROJECT_DIR/SDL2-2.0.14/
  - export CC="gcc -msse2 -march=i686 -m32 -ggdb -O2"
  - ./configure --disable-dependency-tracking --enable-audio --enable-video --enable-events --disable-render --enable-joystick --disable-haptic --disable-power --enable-threads --enable-timers --enable-loadso --enable-video-opengl --enable-x11-shared --enable-video-x11 --enable-video-x11-xrandr --enable-video-x11-scrnsaver --enable-video-x11-xinput --disable-video-x11-xshape --disable-video-x11-xdbe --disable-libudev --disable-dbus --disable-ibus --enable-sdl-dlopen --disable-video-opengles --disable-cpuinfo --disable-assembly --disable-atomic --enable-alsa
  - make -j$(nproc --all)
  - mkdir -p ../sdl2-linux
  - make install DESTDIR=$CI_PROJECT_DIR/sdl2-linux
  - cd ../
  - mkdir out
  - cd out
  - export CC="gcc -m32"
  - export CXX="gcc -m32"
  - cmake -DCMAKE_PREFIX_PATH=$CI_PROJECT_DIR/sdl2-linux/usr/local -DXASH_DOWNLOAD_DEPENDENCIES=yes -DXASH_STATIC=ON -DXASH_DLL_LOADER=ON -DXASH_VGUI=ON -DMAINUI_USE_STB=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo ../
  - make -j$(nproc --all)
  - mkdir artifacts
  - cp ../scripts/xash3d.sh artifacts
  - cp engine/xash3d artifacts
  - cp mainui/libxashmenu.so artifacts
  - cp vgui_support/libvgui_support.so artifacts
  - cp vgui_support/vgui.so artifacts
  - cp $CI_PROJECT_DIR/sdl2-linux/usr/local/lib/$(readlink $CI_PROJECT_DIR/sdl2-linux/usr/local/lib/libSDL2-2.0.so.0) artifacts/libSDL2-2.0.so.0
  artifacts:
    paths:
    - out/artifacts/

coverity_scan:
  stage: coverity_scan
  only:
    refs:
      - master
  before_script:
  - dpkg --add-architecture i386
  - apt update
  - apt install -y wget curl git ccache cmake p7zip-full gcc-multilib g++-multilib build-essential libx11-dev:i386 libxext-dev:i386 libgl1-mesa-dev libasound-dev zlib1g:i386 libstdc++6:i386
  - mkdir -p ccache
  #- curl -o /tmp/cov-analysis-linux64.tgz https://scan.coverity.com/download/linux64 --form project=$COVERITY_SCAN_PROJECT_NAME --form token=$COVERITY_SCAN_TOKEN
  - wget -nv -O /tmp/cov-analysis-linux64.tgz https://scan.coverity.com/download/linux64 --post-data "token=$COVERITY_SCAN_TOKEN&project=tyabus%2Fxash3d"
  - tar xfz /tmp/cov-analysis-linux64.tgz
  - export PATH="/usr/lib/ccache:$PATH"
  - export CCACHE_BASEDIR="$PWD"
  - export CCACHE_DIR="$PWD/ccache"
  - export CCACHE_COMPILERCHECK=content
  - ccache --zero-stats || true
  - ccache --show-stats || true
  after_script:
  - export CCACHE_DIR="$PWD/ccache"
  - ccache --show-stats
  script:
  - curl -s http://libsdl.org/release/SDL2-2.0.14.tar.gz | tar xzf -
  - cd $CI_PROJECT_DIR/SDL2-2.0.14/
  - export CC="gcc -msse2 -march=i686 -m32 -ggdb -O2"
  - ./configure --disable-dependency-tracking --enable-audio --enable-video --enable-events --disable-render --enable-joystick --disable-haptic --disable-power --enable-threads --enable-timers --enable-loadso --enable-video-opengl --enable-x11-shared --enable-video-x11 --enable-video-x11-xrandr --enable-video-x11-scrnsaver --enable-video-x11-xinput --disable-video-x11-xshape --disable-video-x11-xdbe --disable-libudev --disable-dbus --disable-ibus --enable-sdl-dlopen --disable-video-opengles --disable-cpuinfo --disable-assembly --disable-atomic --enable-alsa
  - make -j$(nproc --all)
  - mkdir -p ../sdl2-linux
  - make install DESTDIR=$CI_PROJECT_DIR/sdl2-linux
  - cd ../
  - export CC="gcc -m32"
  - export CXX="gcc -m32"
  - cmake -DCMAKE_PREFIX_PATH=$CI_PROJECT_DIR/sdl2-linux/usr/local -DXASH_DOWNLOAD_DEPENDENCIES=yes -DXASH_STATIC=ON -DXASH_DLL_LOADER=ON -DXASH_VGUI=ON -DMAINUI_USE_STB=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo
  - cov-analysis-linux64-*/bin/cov-build --dir cov-int make -j1
  - cov-analysis-linux64-*/bin/cov-import-scm --dir cov-int --scm git --log cov-int/scm_log.txt 2>&1
  - tar cfz cov-int.tar.gz cov-int
  - curl https://scan.coverity.com/builds?project=$COVERITY_SCAN_PROJECT_NAME --form token=$COVERITY_SCAN_TOKEN --form email=$GITLAB_USER_EMAIL --form file=@cov-int.tar.gz --form version="`git describe --tags`" --form description="`git describe --tags` / $CI_COMMIT_TITLE / $CI_COMMIT_REF_NAME:$CI_PIPELINE_ID "
